export {default as AboutUsPage} from './AboutUsPage'
export {default as CopyrightPage} from './CopyrightPage'
export {default as DisclaimerPage} from './DisclaimerPage'
export {default as FormattingPage} from './FormattinPage'
export {default as HomePage} from './HomePage'
export {default as SoftwareToolsPage} from './SoftwareToolsPage'
export {default as VideoTutorialsPage} from './VideoTutorialsPage'
