export {default as ArticlePage} from './ArticlePage'
export {default as CopyrightPage} from './CopyrightPage'
export {default as DisclaimerPage} from './DisclaimerPage'
export {default as HomePage} from './HomePage'
export {default as TeamPage} from './TeamPage'
